DROP DATABASE `db_imajeur`;

CREATE DATABASE `db_imajeur`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
/*
CONNECT `db_imajeur`;*/

START TRANSACTION;

CREATE TABLE `tbl_user` (
    `USER_id`          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `USER_email`       VARCHAR(256) NOT NULL,
    `USER_first_name`  VARCHAR(100) NOT NULL,
    `USER_last_name`   VARCHAR(100) NOT NULL,
    `USER_dob`         DATE NOT NULL,
    `USER_gender`      VARCHAR(100) NOT NULL,
    `USER_hash`        VARCHAR(256) NOT NULL,
    `USER_salt`        VARCHAR(256) NOT NULL,
    /*`USER_rights`    VARCHAR(20) NOT NULL DEFAULT 'USER', -- & 'ADMIN' & 'MOD'*/
    `USER_public`      BOOL NOT NULL DEFAULT TRUE,
    `USER_avatar_path` VARCHAR(256),
    PRIMARY KEY (`USER_id`)
    );

CREATE TABLE `tbl_imaje` (
    `IMAJE_id`      INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJE_id_user` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJE_id_user`) REFERENCES `tbl_user` (`USER_id`)
    );

CREATE TABLE `tbl_imajeurie` (
    `IMAJEURIE_id`      INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJEURIE_name`    INTEGER UNSIGNED NOT NULL,
    `IMAJEURIE_id_user` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJEURIE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJEURIE_id_user`) REFERENCES `tbl_user` (`USER_id`)
    );

CREATE TABLE `tbl_imaje_imajeurie` (
    `IMAJE_IMAJEURIE_id` INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJE_id`           INTEGER UNSIGNED NOT NULL,
    `IMAJEURIE_id`       INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJE_IMAJEURIE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJE_id`) REFERENCES `tbl_imaje` (`IMAJE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJEURIE_id`) REFERENCES `tbl_imajeurie` (`IMAJEURIE_id`)
    );

CREATE TABLE `tbl_hastag` (
    `HASTAG_id`    INTEGER UNSIGNED AUTO_INCREMENT,
    `HASTAG_value` VARCHAR(100),
    PRIMARY KEY (`HASTAG_id`),
    UNIQUE KEY (`HASTAG_value`)
    );

CREATE TABLE `tbl_haskeyword` (
    `HASKEYWORD_id`         INTEGER UNSIGNED AUTO_INCREMENT,
    `HASKEYWORD_id_doc`     INTEGER UNSIGNED NOT NULL,
    `HASKEYWORD_id_keyword` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`HASKEYWORD_id`),
    CONSTRAINT FOREIGN KEY (`HASKEYWORD_id_doc`) REFERENCES `tbl_doc` (`DOC_id`),
    CONSTRAINT FOREIGN KEY (`HASKEYWORD_id_keyword`) REFERENCES `tbl_keyword` (`KEYWORD_id`)
    );

CREATE TABLE `tbl_cookie` (
    `COOKIE_id`         INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `COOKIE_hash`       VARCHAR(256) NOT NULL,
    `COOKIE_session_id` VARCHAR(256) NOT NULL,
    `COOKIE_timestamp`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `COOKIE_id_user`    INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`COOKIE_id`),
    CONSTRAINT FOREIGN KEY (`COOKIE_id_user`) REFERENCES `tbl_user` (`USER_id`)
    );

CREATE TABLE `tbl_user_registering` (
    `USER_REGISTERING_id`     INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `EMAIL_CONFIRM_hash`      VARCHAR(128) NOT NULL,
    `EMAIL_CONFIRM_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `USER_email`              VARCHAR(256) NOT NULL,
    `USER_first_name`         VARCHAR(100) NOT NULL,
    `USER_last_name`          VARCHAR(100) NOT NULL,
    `USER_hash`               VARCHAR(256) NOT NULL,
    `USER_salt`               VARCHAR(256) NOT NULL,
    PRIMARY KEY (`USER_REGISTERING_id`)
    );

CREATE TABLE `tbl_forgot_password` (
    `FORGOT_PASSWORD_id`        INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `FORGOT_PASSWORD_hash`      VARCHAR(256) NOT NULL,
    `FORGOT_PASSWORD_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `FORGOT_PASSWORD_id_user`   INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`FORGOT_PASSWORD_id`),
    CONSTRAINT FOREIGN KEY (`FORGOT_PASSWORD_id_user`) REFERENCES `tbl_user` (`USER_id`)
    );