DROP DATABASE `db_imajeur`;

CREATE DATABASE `db_imajeur`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CONNECT `db_imajeur`;

START TRANSACTION;

CREATE TABLE `tbl_imajeur` (
    `IMAJEUR_id`           INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `IMAJEUR_email`        VARCHAR(256) NOT NULL,
    `IMAJEUR_first_name`   VARCHAR(100) NOT NULL,
    `IMAJEUR_last_name`    VARCHAR(100) NOT NULL,
    `IMAJEUR_dob`          DATE NOT NULL,
    `IMAJEUR_gender`       VARCHAR(100) NOT NULL,
    `IMAJEUR_hash`         VARCHAR(256) NOT NULL,
    `IMAJEUR_salt`         VARCHAR(256) NOT NULL,
    /*`IMAJEUR_rights`     VARCHAR(20) NOT NULL DEFAULT 'USER', -- & 'ADMIN' & 'MOD'*/
    `IMAJEUR_public`       BOOL NOT NULL DEFAULT TRUE,
    `IMAJEUR_avatar_path`  VARCHAR(256),
    `IMAJEUR_registration` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`IMAJEUR_id`)
    );

CREATE TABLE `tbl_imaje` (
    `IMAJE_id`      INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJE_id_imajeur` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJE_id_imajeur`) REFERENCES `tbl_imajeur` (`IMAJEUR_id`)
    );

CREATE TABLE `tbl_imajeurie` (
    `IMAJEURIE_id`      INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJEURIE_name`    VARCHAR(100),
    `IMAJEURIE_id_imajeur` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJEURIE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJEURIE_id_imajeur`) REFERENCES `tbl_imajeur` (`IMAJEUR_id`)
    );

CREATE TABLE `tbl_imaje_imajeurie` (
    `IMAJE_IMAJEURIE_id` INTEGER UNSIGNED AUTO_INCREMENT,
    `IMAJE_id`           INTEGER UNSIGNED NOT NULL,
    `IMAJEURIE_id`       INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`IMAJE_IMAJEURIE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJE_id`)     REFERENCES `tbl_imaje` (`IMAJE_id`),
    CONSTRAINT FOREIGN KEY (`IMAJEURIE_id`) REFERENCES `tbl_imajeurie` (`IMAJEURIE_id`)
    );

CREATE TABLE `tbl_comment` (
    `COMMENT_id`           INTEGER UNSIGNED AUTO_INCREMENT,
    `COMMENT_id_poster`    INTEGER UNSIGNED NOT NULL,
    `COMMENT_text`         VARCHAR(1000),
    `COMMENT_post_time`    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `COMMENT_edit_time`    TIMESTAMP,
    `COMMENT_id_imajeurie` INTEGER UNSIGNED,
    `COMMENT_id_imajeur`   INTEGER UNSIGNED,
    `COMMENT_id_imaje`     INTEGER UNSIGNED,
    CONSTRAINT FOREIGN KEY (`COMMENT_id_poster`)    REFERENCES `tbl_imajeur` (`IMAJEUR_id`),
    CONSTRAINT FOREIGN KEY (`COMMENT_id_imajeurie`) REFERENCES `tbl_imajeurie` (`IMAJEURIE_id`),
    CONSTRAINT FOREIGN KEY (`COMMENT_id_imajeur`)   REFERENCES `tbl_imajeur` (`IMAJEUR_id`),
    CONSTRAINT FOREIGN KEY (`COMMENT_id_imaje`)     REFERENCES `tbl_imaje` (`IMAJE_id`),
    PRIMARY KEY (`COMMENT_id`)
    );

CREATE TABLE `tbl_hashtag` (
    `HASHTAG_id`    INTEGER UNSIGNED AUTO_INCREMENT,
    `HASHTAG_value` VARCHAR(100),
    PRIMARY KEY (`HASHTAG_id`),
    UNIQUE KEY (`HASHTAG_value`)
    );

CREATE TABLE `tbl_hashashtag` (
    `HASHASHTAG_id`         INTEGER UNSIGNED AUTO_INCREMENT,
    `HASHASHTAG_id_imaje`   INTEGER UNSIGNED NOT NULL,
    `HASHASHTAG_id_hashtag` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`HASHASHTAG_id`),
    CONSTRAINT FOREIGN KEY (`HASHASHTAG_id_hashtag`) REFERENCES `tbl_hashtag` (`HASHTAG_id`)
    );

CREATE TABLE `tbl_cookie` (
    `COOKIE_id`         INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `COOKIE_hash`       VARCHAR(256) NOT NULL,
    `COOKIE_session_id` VARCHAR(256) NOT NULL,
    `COOKIE_timestamp`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `COOKIE_id_imajeur`    INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`COOKIE_id`),
    CONSTRAINT FOREIGN KEY (`COOKIE_id_imajeur`) REFERENCES `tbl_imajeur` (`IMAJEUR_id`)
    );

CREATE TABLE `tbl_imajeur_registering` (
    `IMAJEUR_REGISTERING_id`  INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `EMAIL_CONFIRM_hash`      VARCHAR(128) NOT NULL,
    `EMAIL_CONFIRM_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `IMAJEUR_email`           VARCHAR(256) NOT NULL,
    `IMAJEUR_first_name`      VARCHAR(100) NOT NULL,
    `IMAJEUR_last_name`       VARCHAR(100) NOT NULL,
    `IMAJEUR_hash`            VARCHAR(256) NOT NULL,
    `IMAJEUR_salt`            VARCHAR(256) NOT NULL,
    PRIMARY KEY (`IMAJEUR_REGISTERING_id`)
    );

CREATE TABLE `tbl_forgot_password` (
    `FORGOT_PASSWORD_id`         INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `FORGOT_PASSWORD_hash`       VARCHAR(256) NOT NULL,
    `FORGOT_PASSWORD_timestamp`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `FORGOT_PASSWORD_id_imajeur` INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (`FORGOT_PASSWORD_id`),
    CONSTRAINT FOREIGN KEY (`FORGOT_PASSWORD_id_imajeur`) REFERENCES `tbl_imajeur` (`IMAJEUR_id`)
    );

GRANT INSERT, SELECT, UPDATE ON db_imajeur.* TO php;